package probe

// question.go — the consumable question queue.
//
// Questions are generated, used once and thrown away. Nothing is reused, which
// is what makes a cache attack impossible without any bookkeeping: there is no
// bank to memorise, no alias table to maintain, no seed to steer. The cost is
// that a question has to exist before it can be asked, which is what this file
// is about.
//
// Two producers, deliberately unlike each other:
//
//	math       generated in code. The answer is KNOWN, so a mismatch is the
//	           node's fault and never needs a re-check panel. False positives
//	           are zero, which is why it carries the largest share.
//	the rest   generated by the prober's own llama. What it returns is a DRAFT
//	           answer, not ground truth — an LLM never judges, it only proposes.
//	           A disagreement later goes to a majority vote among other nodes,
//	           and if they side with the node the QUESTION is discarded.
//
// So a wrong draft costs one thrown-away question, never an unfair failure.

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"strconv"
	"strings"
)

// Category is a question kind. The mix is weighted toward math because it is
// the only one whose answer is certain.
type Category string

const (
	// Written in code. Certain answers, unbounded supply, and nothing a
	// generator node could leak in advance.
	CatMath     Category = "math"
	CatSequence Category = "sequence"
	CatUnits    Category = "units"

	// Written by a model.
	CatGeography Category = "geography"
	CatElement   Category = "element"
	CatCurrency  Category = "currency"
)

// categoryMix is the sampling weight per category.
//
// Code-generated categories carry the majority (55%) because their answers are
// certain: a mismatch is the node's fault and never needs a re-check panel.
//
// 🔴 WHAT DECIDES A CATEGORY'S PLACE HERE IS ITS ANSWER SPACE, not how
// interesting the question is. Two categories were removed outright for failing
// that test:
//
//	animal   "how many legs" has four real answers. A node replying "four" to
//	         everything scored about 40%.
//	colour   about ten answers, so roughly 15% for free.
//
// No amount of extra QUESTIONS fixes a small ANSWER space — the guesser does
// not read the question. Every category below has hundreds of possible answers
// (capitals, elements, currencies) or unbounded ones (the numeric three).
//
// Binary-choice forms were considered and rejected for the same reason: "which
// is larger, 47 or 74" hands out 50% to a coin.
var categoryMix = []struct {
	cat    Category
	weight int
}{
	{CatMath, 35},
	{CatSequence, 10},
	{CatUnits, 10},
	{CatGeography, 15},
	{CatElement, 15},
	{CatCurrency, 15},
}

// Question is one item of the queue.
//
// Fewshot travels WITH the question rather than living in a global. Measurement
// found the examples teach the model what KIND of answer is wanted: with
// numeric-only examples, "Which continent is Egypt in?" came back as "3". So the
// examples have to match the category being asked, which makes them a property
// of the item, not of the prober.
type Question struct {
	ID       int64
	Category Category
	Q        string
	Draft    string // the expected answer. For math it is certain; otherwise a draft
	Fewshot  []QA   // exactly two, matching this category
}

// QA is one few-shot example.
type QA struct {
	Q string `json:"q"`
	A string `json:"a"`
}

// encodeFewshot / decodeFewshot move the examples in and out of one text
// column. JSON rather than a delimiter because the examples are model-written
// and will eventually contain whatever character was chosen as a separator.
func encodeFewshot(fs []QA) string {
	b, err := json.Marshal(fs)
	if err != nil {
		return "[]"
	}
	return string(b)
}

func decodeFewshot(s string) []QA {
	var fs []QA
	if err := json.Unmarshal([]byte(s), &fs); err != nil {
		return nil // a question with no examples is still askable, just weaker
	}
	return fs
}

// BuildPrompt assembles what actually goes to the node.
//
//	Give only the answer. No explanation. Q: <ex1> A: <a1> Q: <ex2> A: <a2> Q: <target> A:
//
// Space-joined on one line, not newline-joined — this is the form that was
// measured, and the stop sequence "\n" depends on the model producing the first
// newline itself.
//
// The lead-in is "Give only the answer", NOT "Answer with one word only":
// the one-word phrasing truncated legitimate two-word answers like
// "South America" and "New Delhi", failing honest nodes.
func (q Question) BuildPrompt() string {
	var b strings.Builder
	b.WriteString("Give only the answer. No explanation. ")
	for _, ex := range q.Fewshot {
		b.WriteString("Q: ")
		b.WriteString(ex.Q)
		b.WriteString(" A: ")
		b.WriteString(ex.A)
		b.WriteString(" ")
	}
	b.WriteString("Q: ")
	b.WriteString(q.Q)
	b.WriteString(" A:")
	return b.String()
}

// ---------------------------------------------------------------------------
// math — generated in code
// ---------------------------------------------------------------------------

// mathFewshot are the examples shipped with every math question. Both answers
// are numbers, which is the answer shape a math question wants.
var mathFewshot = []QA{
	{Q: "What is 12 + 7?", A: "19"},
	{Q: "What is 40 - 15?", A: "25"},
}

// newMathQuestion builds an addition or subtraction, two or three digits.
//
// Multiplication is deliberately excluded: 3B-class models get two-digit
// products wrong often enough that the question would measure model size rather
// than whether the node is answering at all.
//
// Subtraction is ordered so the result is never negative — a minus sign is a
// second token and an extra way for a correct node to look wrong.
//
// Three-digit operands appear half the time. Two-digit alone gives 16,200
// distinct questions, which sounds like plenty until the same node is probed
// for months; adding the wider range costs nothing and takes it past 800,000.
func newMathQuestion(rng *rand.Rand) Question {
	lo, hi := 10, 99
	if rng.Intn(2) == 0 {
		lo, hi = 100, 999
	}
	span := hi - lo + 1
	a := rng.Intn(span) + lo
	b := rng.Intn(span) + lo

	if rng.Intn(2) == 0 {
		return Question{
			Category: CatMath,
			Q:        fmt.Sprintf("What is %d + %d?", a, b),
			Draft:    strconv.Itoa(a + b),
			Fewshot:  mathFewshot,
		}
	}
	if b > a {
		a, b = b, a
	}
	return Question{
		Category: CatMath,
		Q:        fmt.Sprintf("What is %d - %d?", a, b),
		Draft:    strconv.Itoa(a - b),
		Fewshot:  mathFewshot,
	}
}

// sequenceFewshot shows the shape: a run of numbers, one number back.
var sequenceFewshot = []QA{
	{Q: "What comes next: 2, 4, 6, 8?", A: "10"},
	{Q: "What comes next: 5, 10, 15, 20?", A: "25"},
}

// newSequenceQuestion builds an arithmetic run and asks for the next term.
//
// Arithmetic steps only — a geometric run reaches four digits by the fifth term
// and turns into the multiplication question that is banned above.
//
// The answer is an ordinary number, so the answer space is unbounded and a
// guesser gets nothing. That is the whole reason this category exists: it adds
// variety without adding a small set of things to guess from.
func newSequenceQuestion(rng *rand.Rand) Question {
	start := rng.Intn(20) + 1 // 1..20
	step := rng.Intn(11) + 2  // 2..12
	terms := make([]string, 4)
	for i := range terms {
		terms[i] = strconv.Itoa(start + i*step)
	}
	return Question{
		Category: CatSequence,
		Q:        fmt.Sprintf("What comes next: %s?", strings.Join(terms, ", ")),
		Draft:    strconv.Itoa(start + 4*step),
		Fewshot:  sequenceFewshot,
	}
}

// unitsFewshot keeps the answer shape numeric.
var unitsFewshot = []QA{
	{Q: "How many centimeters are in 3 meters?", A: "300"},
	{Q: "How many grams are in 4 kilograms?", A: "4000"},
}

// unitConversions are the metric steps used. Powers of ten only: the point is a
// question whose answer is certain, not a units exam, and a factor like 2.54
// would invite rounding disagreements that fail honest nodes.
var unitConversions = []struct {
	from, to string
	factor   int
}{
	{"meters", "centimeters", 100},
	{"meters", "millimeters", 1000},
	{"centimeters", "millimeters", 10},
	{"kilometers", "meters", 1000},
	{"kilograms", "grams", 1000},
	{"liters", "milliliters", 1000},
}

// newUnitsQuestion builds a metric conversion.
//
// It is multiplication, but only by 10, 100 or 1000 — appending zeros, which
// even a small model does reliably. That is a different task from the two-digit
// products the mix excludes.
func newUnitsQuestion(rng *rand.Rand) Question {
	c := unitConversions[rng.Intn(len(unitConversions))]
	n := rng.Intn(98) + 2 // 2..99
	return Question{
		Category: CatUnits,
		Q:        fmt.Sprintf("How many %s are in %d %s?", c.to, n, c.from),
		Draft:    strconv.Itoa(n * c.factor),
		Fewshot:  unitsFewshot,
	}
}

// codeSpec is a category written in code rather than by a model.
//
// Collected in one table so the refill loop treats them uniformly. They share
// three properties the model-written ones do not have: the answer is certain,
// the supply is unbounded, and nothing about them can leak to whichever node
// writes the other questions.
type codeSpec struct {
	cat Category
	gen func(*rand.Rand) Question
}

var codeSpecs = []codeSpec{
	{CatMath, newMathQuestion},
	{CatSequence, newSequenceQuestion},
	{CatUnits, newUnitsQuestion},
}

// ---------------------------------------------------------------------------
// llama-generated categories
// ---------------------------------------------------------------------------

// genSpec is how one category asks a model for a batch. Only the topic differs
// between categories — the output contract lives in genSystem, shared by all of
// them, so changing the line format is one edit and not three.
type genSpec struct {
	cat   Category
	topic string
}

// genBatchLines is how many lines a generation call asks for.
//
// 22, not 20: parseBatch spends the first two usable lines on the few-shot pair,
// so a batch of 20 yields 18 askable questions.
const genBatchLines = 22

// genSystem is the output contract, sent as the system message.
//
// It goes in `system` rather than being prepended to the prompt because an
// instruct model follows format rules markedly better from the system role —
// measured against a run that put all of this in the user turn.
//
// Kept free of any topic wording: the same contract has to hold for geography,
// animals and colour, and a rule that mentions countries would leak into the
// colour batch.
var genSystem = fmt.Sprintf(`You write quiz questions for an automated test.
Output exactly %d lines and nothing else.
Each line: <question> | <answer>
The answer must be a single common English word or number.
Never ask anything with more than one defensible answer.
No numbering, no blank lines, no commentary.`, genBatchLines)

// genSpecs are the per-category topics.
//
// 🔴 EVERY TOPIC HERE IS CHOSEN FOR THE SIZE OF ITS ANSWER SPACE. Continents
// were dropped from geography for having seven answers, and the animal and
// colour categories were removed outright for having four and ten — a node
// replying "four" or "blue" to everything scored 30-40% without reading the
// question. What survives has hundreds of answers each:
//
//	capitals and cities   ~200 countries, and the reverse direction doubles
//	                      the question supply from the same knowledge
//	elements              118 symbols, each one or two letters, no ambiguity
//	currencies            ~150, a handful shared (the euro) and harmless
//
// All avoid the banned kinds: letter counting and string reversal (tokeniser
// artefacts, not knowledge), date arithmetic, dates and biographical detail,
// superlatives (too few possible questions), and anything with more than one
// defensible answer — which is why "the opposite of hot" and "the language
// spoken in X" are not here.
var genSpecs = []genSpec{
	{CatGeography, "Topic: capital cities of well-known countries, and which country a well-known city is in. Mix both directions."},
	{CatElement, "Topic: chemical elements — ask for the chemical symbol given the element's name."},
	{CatCurrency, "Topic: the currency used in well-known countries."},
}

// parseBatch turns a generation response into questions.
//
// The first two usable lines become the few-shot pair and are NOT returned as
// questions — their answers are already in the prompt, so asking them would
// measure copying rather than knowledge.
//
// Lines that do not parse are skipped rather than failing the batch: models
// intersperse numbering and stray prose no matter how the prompt is worded, and
// one bad line should not cost the other nineteen.
func parseBatch(cat Category, raw string) []Question {
	var pairs []QA
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, "|", 2)
		if len(parts) != 2 {
			continue
		}
		q := strings.TrimSpace(parts[0])
		a := strings.TrimSpace(parts[1])
		// Strip a leading "1." / "1)" the model added despite being told not to.
		q = strings.TrimSpace(strings.TrimLeft(q, "0123456789.)- "))
		if q == "" || a == "" {
			continue
		}
		// A multi-sentence answer means the model ignored the format; scoring
		// only looks at the first few tokens so it would fail anyway.
		if len(a) > 40 || strings.Contains(a, "|") {
			continue
		}
		pairs = append(pairs, QA{Q: q, A: a})
	}
	if len(pairs) < 3 {
		return nil // not enough to spare two for examples
	}

	fewshot := []QA{pairs[0], pairs[1]}
	out := make([]Question, 0, len(pairs)-2)
	for _, p := range pairs[2:] {
		out = append(out, Question{Category: cat, Q: p.Q, Draft: p.A, Fewshot: fewshot})
	}
	return out
}

// pickCategory samples a category by weight.
func pickCategory(rng *rand.Rand) Category {
	total := 0
	for _, m := range categoryMix {
		total += m.weight
	}
	n := rng.Intn(total)
	for _, m := range categoryMix {
		if n < m.weight {
			return m.cat
		}
		n -= m.weight
	}
	return CatMath
}
