package probe

// question.go — the consumable question queue.
//
// Questions are generated, used once and thrown away. Nothing is reused, which
// is what makes a cache attack impossible without any bookkeeping: there is no
// bank to memorise, no alias table to maintain, no seed to steer. The cost is
// that a question has to exist before it can be asked, which is what this file
// is about.
//
// Two producers, deliberately unlike each other:
//
//	math       generated in code. The answer is KNOWN, so a mismatch is the
//	           node's fault and never needs a re-check panel. False positives
//	           are zero, which is why it carries the largest share.
//	the rest   generated by the prober's own llama. What it returns is a DRAFT
//	           answer, not ground truth — an LLM never judges, it only proposes.
//	           A disagreement later goes to a majority vote among other nodes,
//	           and if they side with the node the QUESTION is discarded.
//
// So a wrong draft costs one thrown-away question, never an unfair failure.

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"strconv"
	"strings"
)

// Category is a question kind. The mix is weighted toward math because it is
// the only one whose answer is certain.
type Category string

const (
	CatMath      Category = "math"
	CatGeography Category = "geography"
	CatAnimal    Category = "animal"
	CatColor     Category = "color"
)

// categoryMix is the sampling weight per category (llama-faucet-probe.md §7).
// math 50% because it needs no re-check; the rest split the remainder.
var categoryMix = []struct {
	cat    Category
	weight int
}{
	{CatMath, 50},
	{CatGeography, 20},
	{CatAnimal, 15},
	{CatColor, 15},
}

// Question is one item of the queue.
//
// Fewshot travels WITH the question rather than living in a global. Measurement
// found the examples teach the model what KIND of answer is wanted: with
// numeric-only examples, "Which continent is Egypt in?" came back as "3". So the
// examples have to match the category being asked, which makes them a property
// of the item, not of the prober.
type Question struct {
	ID       int64
	Category Category
	Q        string
	Draft    string // the expected answer. For math it is certain; otherwise a draft
	Fewshot  []QA   // exactly two, matching this category
}

// QA is one few-shot example.
type QA struct {
	Q string `json:"q"`
	A string `json:"a"`
}

// encodeFewshot / decodeFewshot move the examples in and out of one text
// column. JSON rather than a delimiter because the examples are model-written
// and will eventually contain whatever character was chosen as a separator.
func encodeFewshot(fs []QA) string {
	b, err := json.Marshal(fs)
	if err != nil {
		return "[]"
	}
	return string(b)
}

func decodeFewshot(s string) []QA {
	var fs []QA
	if err := json.Unmarshal([]byte(s), &fs); err != nil {
		return nil // a question with no examples is still askable, just weaker
	}
	return fs
}

// BuildPrompt assembles what actually goes to the node.
//
//	Give only the answer. No explanation. Q: <ex1> A: <a1> Q: <ex2> A: <a2> Q: <target> A:
//
// Space-joined on one line, not newline-joined — this is the form that was
// measured, and the stop sequence "\n" depends on the model producing the first
// newline itself.
//
// The lead-in is "Give only the answer", NOT "Answer with one word only":
// the one-word phrasing truncated legitimate two-word answers like
// "South America" and "New Delhi", failing honest nodes.
func (q Question) BuildPrompt() string {
	var b strings.Builder
	b.WriteString("Give only the answer. No explanation. ")
	for _, ex := range q.Fewshot {
		b.WriteString("Q: ")
		b.WriteString(ex.Q)
		b.WriteString(" A: ")
		b.WriteString(ex.A)
		b.WriteString(" ")
	}
	b.WriteString("Q: ")
	b.WriteString(q.Q)
	b.WriteString(" A:")
	return b.String()
}

// ---------------------------------------------------------------------------
// math — generated in code
// ---------------------------------------------------------------------------

// mathFewshot are the examples shipped with every math question. Both answers
// are numbers, which is the answer shape a math question wants.
var mathFewshot = []QA{
	{Q: "What is 12 + 7?", A: "19"},
	{Q: "What is 40 - 15?", A: "25"},
}

// newMathQuestion builds a two-digit addition or subtraction.
//
// Multiplication is deliberately excluded: 3B-class models get two-digit
// products wrong often enough that the question would measure model size rather
// than whether the node is answering at all.
//
// Subtraction is ordered so the result is never negative — a minus sign is a
// second token and an extra way for a correct node to look wrong.
func newMathQuestion(rng *rand.Rand) Question {
	a := rng.Intn(90) + 10 // 10..99
	b := rng.Intn(90) + 10
	if rng.Intn(2) == 0 {
		return Question{
			Category: CatMath,
			Q:        fmt.Sprintf("What is %d + %d?", a, b),
			Draft:    strconv.Itoa(a + b),
			Fewshot:  mathFewshot,
		}
	}
	if b > a {
		a, b = b, a
	}
	return Question{
		Category: CatMath,
		Q:        fmt.Sprintf("What is %d - %d?", a, b),
		Draft:    strconv.Itoa(a - b),
		Fewshot:  mathFewshot,
	}
}

// ---------------------------------------------------------------------------
// llama-generated categories
// ---------------------------------------------------------------------------

// genSpec is how one category asks the local model for a batch.
//
// Every prompt demands the same "<question> | <answer>" line format so one
// parser handles all of them, and every one insists on a single common English
// word so the answer stays inside the scoring window.
type genSpec struct {
	cat    Category
	prompt string
}

// genSpecs are the batch-generation prompts.
//
// Only the geography prompt is from the spec (llama-faucet-probe.md §5); animal
// and color are written to the same shape. All three avoid the banned kinds:
// letter counting and string reversal (tokeniser artefacts, not knowledge), date
// arithmetic, dates and biographical detail, and anything with a debatable
// answer.
var genSpecs = []genSpec{
	{CatGeography, `Generate 20 quiz questions about world capitals and continents.
Each must have exactly one common English word as its answer.
Use only well-known countries.
One per line, format: <question> | <answer>. No numbering, no extra text.`},

	{CatAnimal, `Generate 20 quiz questions about common animals: what class an animal
belongs to, or how many legs it has.
Each must have exactly one common English word or number as its answer.
Use only animals a child would recognise.
One per line, format: <question> | <answer>. No numbering, no extra text.`},

	{CatColor, `Generate 20 quiz questions about the usual colour of everyday objects.
Each must have exactly one common English colour word as its answer.
Use only objects with one obvious colour.
One per line, format: <question> | <answer>. No numbering, no extra text.`},
}

// parseBatch turns a generation response into questions.
//
// The first two usable lines become the few-shot pair and are NOT returned as
// questions — their answers are already in the prompt, so asking them would
// measure copying rather than knowledge.
//
// Lines that do not parse are skipped rather than failing the batch: models
// intersperse numbering and stray prose no matter how the prompt is worded, and
// one bad line should not cost the other nineteen.
func parseBatch(cat Category, raw string) []Question {
	var pairs []QA
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, "|", 2)
		if len(parts) != 2 {
			continue
		}
		q := strings.TrimSpace(parts[0])
		a := strings.TrimSpace(parts[1])
		// Strip a leading "1." / "1)" the model added despite being told not to.
		q = strings.TrimSpace(strings.TrimLeft(q, "0123456789.)- "))
		if q == "" || a == "" {
			continue
		}
		// A multi-sentence answer means the model ignored the format; scoring
		// only looks at the first few tokens so it would fail anyway.
		if len(a) > 40 || strings.Contains(a, "|") {
			continue
		}
		pairs = append(pairs, QA{Q: q, A: a})
	}
	if len(pairs) < 3 {
		return nil // not enough to spare two for examples
	}

	fewshot := []QA{pairs[0], pairs[1]}
	out := make([]Question, 0, len(pairs)-2)
	for _, p := range pairs[2:] {
		out = append(out, Question{Category: cat, Q: p.Q, Draft: p.A, Fewshot: fewshot})
	}
	return out
}

// pickCategory samples a category by weight.
func pickCategory(rng *rand.Rand) Category {
	total := 0
	for _, m := range categoryMix {
		total += m.weight
	}
	n := rng.Intn(total)
	for _, m := range categoryMix {
		if n < m.weight {
			return m.cat
		}
		n -= m.weight
	}
	return CatMath
}
